try {
    // ...
} catch (IOException warning) {
    ExceptionReporter.getExceptionReporter().report(warning);
    // Recover from the exception...
}